### PR TITLE
Made discord link mobile responsive

### PR DESCRIPTION
**Pull request by prince-hope1975**
fixed Error associated with the responsiveness of the discord link on faq page 
This is the link to the live preview [here](https://festive-mcclintock-749ef6.netlify.app/)

### CODE REVIEW

**Comment by prince-hope1975** [comment]
The second Pull request made has to do with the copy button.
A message is now displayed when it is clicked on, in contrast to what it was before 
live preview of the current site [here](https://festive-mcclintock-749ef6.netlify.app/)

**Comment by prince-hope1975** [comment]
Bug fixes. 
Made the scrollable text link to discord

**Comment by Bhaney44** [comment]
I'm noticing an abnormality in line 45 `{" "}` of the `landing.js` file. What is the reason for this?

**Comment by ChoiceCoin** [comment]
Please also make sure to merge upstream on this repo. @prince-hope1975

**Pull request closed without merging**
